---
- name: Manage users and corn jobs
  hosts: web-servers
  become: yes
  vars:
    user_name: "anakinskywalker"
  tasks:
    - name: Ensure group develepers exists
      group:
        name: developers
        state: present

    - name: create user
      user:
        name: "{{ user_name }}"
        group: developers
        create_home: yes
        shell: /bin/bash

    - name: set up daily cronjob
      cron:
        name: "daily backup"
        user: "{{ user_name }}"
        job: 'bash /home/"{{ user_name }}"/backup.sh'
        minute: "0"
        hour: "2"
        day: "*"
