---
- name: Ensure group develepers exists
  group:
    name: developers
    state: present

- name: create user
  user:
    name: "anakinskywalker"
    group: developers
    create_home: yes
    shell: /bin/bash
